[package]
name = "trajectory-render"
version = "0.1.0"
authors = ["Leland Batey <lelandbatey@lelandbatey.com>"]

[dependencies]
buddhabrot = {path = "../buddhabrot"}

serde = "1.0"
argparse = "*"
serde_json = "1.0"
crossbeam-channel = "0.3"
