[package]
name = "trajectory-gen"
version = "0.1.0"
authors = ["Leland Batey <lelandbatey@lelandbatey.com>"]

[dependencies]
argparse = "*"
rand = "0.3"
time = "*"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"

buddhabrot = { path = "../buddhabrot" }
